import os

print('Initializing...')
print('\r--reading...\t' + "1%", end='')
os.system("python 读答题纸,把需要预测的(uid,mid)存到'to_predict'中.py")
os.system("python 得到观影记录'uid_records'(读uid.xlsx).py")
print('\r--reading...\t' + "10%", end='')
os.system("python 读电影相似度矩阵,二维map存到'mid_xsd'中.py")
print('\r--reading...\t' + "35%", end='')
os.system("python 存UIDs到srcData.py")
os.system("python 读用户相似度矩阵,二维map存到'uid_xsd'中.py")
print('\r--reading...\t' + "60%", end='')
os.system("python 将uid_xsd排序，xsd高的在上面，存到'uid_xsd_sorted'.py")
print('\r--reading...\t' + "75%", end='')
os.system("python 将mid_xsd排序，xsd高的在上面，存到'mid_xsd_sorted'.py")
print('\r--reading...\t' + "90%", end='')
os.system("python 存MIDs到srcData.py")
os.system("python 构造一个key为mids,value为0的字典.py")
print('\r--reading...\t' + "100%\tok")

print('Analysing...')
os.system('python 根据电影相似度推荐.py')
os.system('python 根据用户相似度推荐.py')

print("\n\nInitialization Data Succeed!!")
